// Renders buildContext() from src/data into api/context.ts.
//
// The serverless function cannot import across the api/ boundary: Vercel does
// not bundle relative imports that leave the functions directory, so a runtime
// `import '../src/data/ask.js'` fails to resolve and the whole module dies with
// FUNCTION_INVOCATION_FAILED. Emitting a data-only module beside the handler
// keeps src/data as the single source of truth without the boundary crossing.
//
// Runs from `prebuild`, so `npm run build` — locally and on Vercel — always
// regenerates before the function is compiled.

import { build } from 'esbuild'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

const OUTPUT = 'api/context.ts'

const scratch = await mkdtemp(join(tmpdir(), 'portfolio-context-'))
const bundle = join(scratch, 'ask.mjs')

try {
  await build({
    entryPoints: ['src/data/ask.ts'],
    outfile: bundle,
    bundle: true,
    platform: 'node',
    format: 'esm',
    logLevel: 'warning',
  })

  const { buildContext } = await import(pathToFileURL(bundle).href)
  const context = buildContext()

  const next = `// GENERATED by scripts/generate-context.mjs — do not edit.
// Source of truth: src/data/ask.ts and the modules under src/data.

export const CONTEXT = ${JSON.stringify(context)}
`

  const current = await readFile(OUTPUT, 'utf8').catch(() => '')
  if (current === next) {
    console.log(`context unchanged (${context.length} chars)`)
  } else {
    await writeFile(OUTPUT, next)
    console.log(`wrote ${OUTPUT} (${context.length} chars)`)
  }
} finally {
  await rm(scratch, { recursive: true, force: true })
}
